# Generated by Django 4.2.4 on 2023-08-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('ratio', models.IntegerField(blank=True, null=True)),
                ('diameter', models.IntegerField(blank=True, null=True)),
                ('load', models.IntegerField(blank=True, null=True)),
                ('speed', models.CharField(blank=True, max_length=2, null=True)),
                ('season', models.CharField(blank=True, choices=[('Tutto', 'Tutto'), ('Estivi', 'Estivi'), ('Invernali', 'Invernali'), ('Per tutte le stagioni', 'Per tutte le stagioni')], default='Tutto', max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('runflat', models.BooleanField(blank=True, null=True)),
                ('dot', models.IntegerField(blank=True, max_length=4, null=True)),
                ('reinforced', models.BooleanField(blank=True, null=True)),
                ('load_c', models.BooleanField(blank=True, null=True)),
                ('on_sale', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('wheel', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='order.wheel')),
            ],
        ),
    ]
