# Generated by Django 4.2.4 on 2023-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='dot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
